name: Workflow test Hello world
on: 
  - push 
jobs: 
  MyfirstJob:
    runs-on: ubuntu-latest
    steps:
      - name: first steps
        run: echo "Hello world" 
      - uses: actions/checkout@v2
      - name: Show files
        run: ls -la
      - name: Execute main
        run: python main.py
      