name: Workflow test Hello world
on: 
  - push 
jobs: 
  MyfirstJob:
    runs-on: ubuntu-latest
    steps:
      - name: first steps
        run: echo "Hello world" 
      - name: Execute main
        run: python main.py